# Generated by Django on 2026-09-20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0004_quizattempt_analysis_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='topic',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='quiz_attempts',
                to='curriculum.topic',
            ),
        ),
    ]
